import React, { Component } from 'react';
import './App.css';
import { BrowserRouter as Router, Route } from 'react-router-dom'
import Landing from './components/Landing';
import Catalog from './components/Catalog';
import Header from './components/Header.js';
import MovieDetail from './components/MovieDetail';


class App extends Component {
  constructor() {
    super()
    this.state = {
      actualUser: '',
      users: {
        user1: {
          name: "Franco",
          movies: [
            { id: 15, isRented: false, title: "Joker", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg", descrShort: "Forever alone in a crowd, failed comedian Arthur Fleck seeks connection as he walks the streets of Gotham City. Arthur wears two masks -- the one he paints for his day job as a clown, and the guise he projects in a futile attempt to feel like he's part of the world around him. Isolated, bullied and disregarded by society, Fleck begins a slow descent into madness as he transforms into the criminal mastermind known as the Joker." },
            { id: 11, isRented: false, title: "Fyre", year: 2019, img: "https://m.media-amazon.com/images/M/MV5BMjQ2NzE1MjYxMV5BMl5BanBnXkFtZTgwMjM3MDQxNzM@._V1_SY1000_SX675_AL_.jpg", descrShort: "The history of the Fyre Music Festival, from its creation through its unraveling." },
            { id: 13, isRented: false, title: "Terminator: Dark Fate", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/5/5f/Terminator_Dark_Fate_poster.jpg", descrShort: "Sarah Connor and a hybrid cyborg human must protect a young girl from a newly modified liquid Terminator from the future." },
            { id: 12, isRented: false, title: "Fast & Furious Presents: Hobbs & Shaw", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/0/00/Fast_%26_Furious_Presents_Hobbs_%26_Shaw_-_theatrical_poster.jpg", descrShort: "DescriptionBrixton Lorr is a cybernetically enhanced soldier who possesses superhuman strength, a brilliant mind and a lethal pathogen that could wipe out half of the world's population. It's now up to hulking lawman Luke Hobbs and lawless operative Deckard Shaw to put aside their past differences and work together to prevent the seemingly indestructible Lorr from destroying humanity." },
            { id: 9, isRented: false, title: "Jumanji: The Next Level", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/3/3c/JumanjiTheNextLevelTeaserPoster.jpg", descrShort: "The four players brave the jungle, desert, mountains and dangerous animals to save the fantastical video game world of Jumanji." },
            { id: 16, isRented: false, title: "John Wick: Chapter 3", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/9/94/John_Wick_Chapter_3_Parabellum.png", descrShort:" After gunning down a member of the High Table  the shadowy international assassins guild -- legendary hit man John Wick finds himself stripped of the organizations protective services. Now stuck with a $14 million bounty on his head, Wick must fight his way through the streets of New York as he becomes the target of the worlds most ruthless killers." },
            { id: 7, isRented: false, title: "Money Heist", year: 2019, img: "https://m.media-amazon.com/images/M/MV5BNmYxZWNlMDAtYzczZC00M2ViLWIwYjctMDg3M2QyN2E1MzlmXkEyXkFqcGdeQXVyNjE4ODA3NTY@._V1_SY1000_CR0,0,675,1000_AL_.jpg", descrShort: "A criminal mastermind who goes by: The Professor has a plan to pull off the biggest heist in recorded history -- to print billions of euros in the Royal Mint of Spain. To help him carry out the ambitious plan, he recruits eight people with certain abilities and who have nothing to lose. The group of thieves take hostages to aid in their negotiations with the authorities, who strategize to come up with a way to capture The Professor. As more time elapses, the robbers prepare for a showdown with the police." },
            { id: 14, isRented: false, title: "Rambo, Last Blood", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/b/b1/Rambo_-_Last_Blood_official_theatrical_poster.jpg", descrShort: "Vietnam War veteran John Rambo tries to find some semblance of peace by raising horses on a ranch in Arizona. He's also developed a special familial bond with a woman named Maria and her teenage granddaughter Gabriela. But when a vicious Mexican cartel kidnaps Gabriela, Rambo crosses the border on a bloody and personal quest to rescue her and punish those responsible." },
            { id: 7, isRented: false, title: "Toy Story 4", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/4/4c/Toy_Story_4_poster.jpg", descrShort: "Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky. The adventurous journey turns into an unexpected reunion as Woody's slight detour leads him to his long-lost friend Bo Peep. As Woody and Bo discuss the old days, they soon start to realize that they're worlds apart when it comes to what they want from life as a toy." },
            { id: 20, isRented: false, title: "Game Night", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/a/a4/Game_Night_%28film%29.png", descrShort:" Max and Annie's weekly game night gets kicked up a notch when Max's brother Brooks arranges a murder mystery party -- complete with fake thugs and federal agents. So when Brooks gets kidnapped, it's all supposed to be part of the game. As the competitors set out to solve the case, they start to learn that neither the game nor Brooks are what they seem to be. The friends soon find themselves in over their heads as each twist leads to another unexpected turn over the course of one chaotic night." },
            { id: 19, isRented: false, title: "Annihilation", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/f/f6/Annihilation_%28film%29.png", descrShort:"Lena, a biologist and former soldier, joins a mission to uncover what happened to her husband inside Area X -- a sinister and mysterious phenomenon that is expanding across the American coastline. Once inside, the expedition discovers a world of mutated landscapes and creatures, as dangerous as it is beautiful, that threatens both their lives and their sanity. " },
            { id: 18, isRented: false, title: "Mission: Impossible – Fallout", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/f/ff/MI_%E2%80%93_Fallout.jpg", descrShort:" Ethan Hunt and the IMF team join forces with CIA assassin August Walker to prevent a disaster of epic proportions. Arms dealer John Lark and a group of terrorists known as the Apostles plan to use three plutonium cores for a simultaneous nuclear attack on the Vatican, Jerusalem and Mecca, Saudi Arabia. When the weapons go missing, Ethan and his crew find themselves in a desperate race against time to prevent them from falling into the wrong hands." },
            { id: 17, isRented: false, title: "Venom", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/1/18/Venom_%282018_film_poster%29.png", descrShort:"Journalist Eddie Brock is trying to take down Carlton Drake, the notorious and brilliant founder of the Life Foundation. While investigating one of Drake's experiments, Eddie's body merges with the alien Venom -- leaving him with superhuman strength and power. Twisted, dark and fueled by rage, Venom tries to control the new and dangerous abilities that Eddie finds so intoxicating. " },
            { id: 10, isRented: false, title: "Ocean's 8", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/d/dd/OceansEightPoster.jpeg", descrShort: "Five years, eight months, 12 days and counting -- that's how long Debbie Ocean has been devising the biggest heist of her life. She knows what it's going to take -- a team of the best people in the field, starting with her partner-in-crime Lou Miller. Together, they recruit a crew of specialists, including jeweler Amita, street con Constance, suburban mom Tammy, hacker Nine Ball, and fashion designer Rose. Their target -- a necklace that's worth more than $150 million." },
            { id: 1, isRented: false, title: "The Lion King",year: 2018, img: "https://img00.deviantart.net/b782/i/2006/207/e/7/the_lion_king_front_cd_cover_by_peachpocket285.jpg", year: 1994, descrShort: "A young lion prince named Simba is born into wealth but raised into incredible misfortune. Trickster uncle, dying father, usurpation. Luckily, an unlikely meerkat-warthog pair take him in and teach him The Ways of the Bum Life. Be prepared for ghostly hallucinations, wild baboons, creepy crawlies." },
            { id: 8, isRented: false, title: "Fast and furious 8", year: 2017, img: "https://m.media-amazon.com/images/M/MV5BMjA2MDM2OTc0MV5BMl5BanBnXkFtZTgwMTg2MzQ4MDI@._V1_.jpg", descrShort: "With Dom and Letty married, Brian and Mia retired and the rest of the crew exonerated, the globe-trotting team has found some semblance of a normal life. They soon face an unexpected challenge when a mysterious woman named Cipher forces Dom to betray them all. Now, they must unite to bring home the man who made them a family and stop Cipher from unleashing chaos." },
            { id: 5, isRented: false, title: "Coco", year: 2017, img: "https://upload.wikimedia.org/wikipedia/en/9/98/Coco_%282017_film%29_poster.jpg", descrShort: "Despite his family's generations-old ban on music, young Miguel dreams of becoming an accomplished musician like his idol Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead." },
            { id: 4, isRented: false, title: "Beauty and the Beast", year: 2016, img: "https://images-na.ssl-images-amazon.com/images/I/51ArFYSFGJL.jpg", descrShort: "Basically the same as the original, except now Hermi-- Emma Wattson plays Belle, fittingly so some would say, given how actively progressive she is regarding women's rights. Rumor has it that in the bonus scenes she whips out a wand and turns Gaston into a toad, but in order to watch those scenes you need to recite a certain incantation." },
            { id: 6, isRented: false, title: "Moana", year: 2016, img: "https://upload.wikimedia.org/wikipedia/en/2/26/Moana_Teaser_Poster.jpg", descrShort: "An adventurous teenager sails out on a daring mission to save her people. During her journey, Moana meets the once-mighty demigod Maui, who guides her in her quest to become a master way-finder. Together they sail across the open ocean on an action-packed voyage, encountering enormous monsters and impossible odds. Along the way, Moana fulfills the ancient quest of her ancestors and discovers the one thing she always sought: her own identity." },
            { id: 2, isRented: false, title: "Beauty and the Beast", year: 1991, img: "https://images-na.ssl-images-amazon.com/images/I/81etFyb9N-L._SL1500_.jpg", descrShort: "A kickass woman named Belle who does not succumb to social norms gets crap from a bunch of village idiots, chief amongst them a total tool named Gaston. Belle shows everyone how great she is when she turns a beast (not Gaston) into a man. Love ensues, but then the villagers fall trap to severe group-think mentality led by the main tool himself." },
            { id: 0, isRented: false, title: "Tarzan", year: 1999, img: "https://vignette.wikia.nocookie.net/disney-fan-fiction/images/4/42/Tarzan_2004_cover.jpg/revision/latest?cb=20140331030811", descrShort: "Tarzan was born into wealth but raised into incredible misfortune. Shiprweck, parents mauled by a jaguar. Luckily, a troop of gorillas took him in, but the Big Daddy gorilla never took a liking to him. That is, until the end when it's too late. Why is it too late? Watch and find out." },
           
            
          ],
          rentedMovies: 0,
          budget: 130
        },
        user2: {
          name: "George",
          movies: [
            { id: 15, isRented: false, title: "Joker", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg", descrShort: "Forever alone in a crowd, failed comedian Arthur Fleck seeks connection as he walks the streets of Gotham City. Arthur wears two masks -- the one he paints for his day job as a clown, and the guise he projects in a futile attempt to feel like he's part of the world around him. Isolated, bullied and disregarded by society, Fleck begins a slow descent into madness as he transforms into the criminal mastermind known as the Joker." },
            { id: 11, isRented: false, title: "Fyre", year: 2019, img: "https://m.media-amazon.com/images/M/MV5BMjQ2NzE1MjYxMV5BMl5BanBnXkFtZTgwMjM3MDQxNzM@._V1_SY1000_SX675_AL_.jpg", descrShort: "The history of the Fyre Music Festival, from its creation through its unraveling." },
            { id: 13, isRented: false, title: "Terminator: Dark Fate", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/5/5f/Terminator_Dark_Fate_poster.jpg", descrShort: "Sarah Connor and a hybrid cyborg human must protect a young girl from a newly modified liquid Terminator from the future." },
            { id: 12, isRented: false, title: "Fast & Furious Presents: Hobbs & Shaw", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/0/00/Fast_%26_Furious_Presents_Hobbs_%26_Shaw_-_theatrical_poster.jpg", descrShort: "DescriptionBrixton Lorr is a cybernetically enhanced soldier who possesses superhuman strength, a brilliant mind and a lethal pathogen that could wipe out half of the world's population. It's now up to hulking lawman Luke Hobbs and lawless operative Deckard Shaw to put aside their past differences and work together to prevent the seemingly indestructible Lorr from destroying humanity." },
            { id: 9, isRented: false, title: "Jumanji: The Next Level", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/3/3c/JumanjiTheNextLevelTeaserPoster.jpg", descrShort: "The four players brave the jungle, desert, mountains and dangerous animals to save the fantastical video game world of Jumanji." },
            { id: 16, isRented: false, title: "John Wick: Chapter 3", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/9/94/John_Wick_Chapter_3_Parabellum.png", descrShort:" After gunning down a member of the High Table  the shadowy international assassins guild -- legendary hit man John Wick finds himself stripped of the organizations protective services. Now stuck with a $14 million bounty on his head, Wick must fight his way through the streets of New York as he becomes the target of the worlds most ruthless killers." },
            { id: 7, isRented: false, title: "Money Heist", year: 2019, img: "https://m.media-amazon.com/images/M/MV5BNmYxZWNlMDAtYzczZC00M2ViLWIwYjctMDg3M2QyN2E1MzlmXkEyXkFqcGdeQXVyNjE4ODA3NTY@._V1_SY1000_CR0,0,675,1000_AL_.jpg", descrShort: "A criminal mastermind who goes by: The Professor has a plan to pull off the biggest heist in recorded history -- to print billions of euros in the Royal Mint of Spain. To help him carry out the ambitious plan, he recruits eight people with certain abilities and who have nothing to lose. The group of thieves take hostages to aid in their negotiations with the authorities, who strategize to come up with a way to capture The Professor. As more time elapses, the robbers prepare for a showdown with the police." },
            { id: 14, isRented: false, title: "Rambo, Last Blood", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/b/b1/Rambo_-_Last_Blood_official_theatrical_poster.jpg", descrShort: "Vietnam War veteran John Rambo tries to find some semblance of peace by raising horses on a ranch in Arizona. He's also developed a special familial bond with a woman named Maria and her teenage granddaughter Gabriela. But when a vicious Mexican cartel kidnaps Gabriela, Rambo crosses the border on a bloody and personal quest to rescue her and punish those responsible." },
            { id: 7, isRented: false, title: "Toy Story 4", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/4/4c/Toy_Story_4_poster.jpg", descrShort: "Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky. The adventurous journey turns into an unexpected reunion as Woody's slight detour leads him to his long-lost friend Bo Peep. As Woody and Bo discuss the old days, they soon start to realize that they're worlds apart when it comes to what they want from life as a toy." },
            { id: 20, isRented: false, title: "Game Night", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/a/a4/Game_Night_%28film%29.png", descrShort:" Max and Annie's weekly game night gets kicked up a notch when Max's brother Brooks arranges a murder mystery party -- complete with fake thugs and federal agents. So when Brooks gets kidnapped, it's all supposed to be part of the game. As the competitors set out to solve the case, they start to learn that neither the game nor Brooks are what they seem to be. The friends soon find themselves in over their heads as each twist leads to another unexpected turn over the course of one chaotic night." },
            { id: 19, isRented: false, title: "Annihilation", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/f/f6/Annihilation_%28film%29.png", descrShort:"Lena, a biologist and former soldier, joins a mission to uncover what happened to her husband inside Area X -- a sinister and mysterious phenomenon that is expanding across the American coastline. Once inside, the expedition discovers a world of mutated landscapes and creatures, as dangerous as it is beautiful, that threatens both their lives and their sanity. " },
            { id: 18, isRented: false, title: "Mission: Impossible – Fallout", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/f/ff/MI_%E2%80%93_Fallout.jpg", descrShort:" Ethan Hunt and the IMF team join forces with CIA assassin August Walker to prevent a disaster of epic proportions. Arms dealer John Lark and a group of terrorists known as the Apostles plan to use three plutonium cores for a simultaneous nuclear attack on the Vatican, Jerusalem and Mecca, Saudi Arabia. When the weapons go missing, Ethan and his crew find themselves in a desperate race against time to prevent them from falling into the wrong hands." },
            { id: 17, isRented: false, title: "Venom", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/1/18/Venom_%282018_film_poster%29.png", descrShort:"Journalist Eddie Brock is trying to take down Carlton Drake, the notorious and brilliant founder of the Life Foundation. While investigating one of Drake's experiments, Eddie's body merges with the alien Venom -- leaving him with superhuman strength and power. Twisted, dark and fueled by rage, Venom tries to control the new and dangerous abilities that Eddie finds so intoxicating. " },
            { id: 10, isRented: false, title: "Ocean's 8", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/d/dd/OceansEightPoster.jpeg", descrShort: "Five years, eight months, 12 days and counting -- that's how long Debbie Ocean has been devising the biggest heist of her life. She knows what it's going to take -- a team of the best people in the field, starting with her partner-in-crime Lou Miller. Together, they recruit a crew of specialists, including jeweler Amita, street con Constance, suburban mom Tammy, hacker Nine Ball, and fashion designer Rose. Their target -- a necklace that's worth more than $150 million." },
            { id: 1, isRented: false, title: "The Lion King",year: 2018, img: "https://img00.deviantart.net/b782/i/2006/207/e/7/the_lion_king_front_cd_cover_by_peachpocket285.jpg", year: 1994, descrShort: "A young lion prince named Simba is born into wealth but raised into incredible misfortune. Trickster uncle, dying father, usurpation. Luckily, an unlikely meerkat-warthog pair take him in and teach him The Ways of the Bum Life. Be prepared for ghostly hallucinations, wild baboons, creepy crawlies." },
            { id: 8, isRented: false, title: "Fast and furious 8", year: 2017, img: "https://m.media-amazon.com/images/M/MV5BMjA2MDM2OTc0MV5BMl5BanBnXkFtZTgwMTg2MzQ4MDI@._V1_.jpg", descrShort: "With Dom and Letty married, Brian and Mia retired and the rest of the crew exonerated, the globe-trotting team has found some semblance of a normal life. They soon face an unexpected challenge when a mysterious woman named Cipher forces Dom to betray them all. Now, they must unite to bring home the man who made them a family and stop Cipher from unleashing chaos." },
            { id: 5, isRented: false, title: "Coco", year: 2017, img: "https://upload.wikimedia.org/wikipedia/en/9/98/Coco_%282017_film%29_poster.jpg", descrShort: "Despite his family's generations-old ban on music, young Miguel dreams of becoming an accomplished musician like his idol Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead." },
            { id: 4, isRented: false, title: "Beauty and the Beast", year: 2016, img: "https://images-na.ssl-images-amazon.com/images/I/51ArFYSFGJL.jpg", descrShort: "Basically the same as the original, except now Hermi-- Emma Wattson plays Belle, fittingly so some would say, given how actively progressive she is regarding women's rights. Rumor has it that in the bonus scenes she whips out a wand and turns Gaston into a toad, but in order to watch those scenes you need to recite a certain incantation." },
            { id: 6, isRented: false, title: "Moana", year: 2016, img: "https://upload.wikimedia.org/wikipedia/en/2/26/Moana_Teaser_Poster.jpg", descrShort: "An adventurous teenager sails out on a daring mission to save her people. During her journey, Moana meets the once-mighty demigod Maui, who guides her in her quest to become a master way-finder. Together they sail across the open ocean on an action-packed voyage, encountering enormous monsters and impossible odds. Along the way, Moana fulfills the ancient quest of her ancestors and discovers the one thing she always sought: her own identity." },
            { id: 2, isRented: false, title: "Beauty and the Beast", year: 1991, img: "https://images-na.ssl-images-amazon.com/images/I/81etFyb9N-L._SL1500_.jpg", descrShort: "A kickass woman named Belle who does not succumb to social norms gets crap from a bunch of village idiots, chief amongst them a total tool named Gaston. Belle shows everyone how great she is when she turns a beast (not Gaston) into a man. Love ensues, but then the villagers fall trap to severe group-think mentality led by the main tool himself." },
            { id: 0, isRented: false, title: "Tarzan", year: 1999, img: "https://vignette.wikia.nocookie.net/disney-fan-fiction/images/4/42/Tarzan_2004_cover.jpg/revision/latest?cb=20140331030811", descrShort: "Tarzan was born into wealth but raised into incredible misfortune. Shiprweck, parents mauled by a jaguar. Luckily, a troop of gorillas took him in, but the Big Daddy gorilla never took a liking to him. That is, until the end when it's too late. Why is it too late? Watch and find out." },
           
            
          ],
          rentedMovies: 0,
          budget: 80
        },
        user3: {
          name: "Matt",
          movies: [
            { id: 15, isRented: false, title: "Joker", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg", descrShort: "Forever alone in a crowd, failed comedian Arthur Fleck seeks connection as he walks the streets of Gotham City. Arthur wears two masks -- the one he paints for his day job as a clown, and the guise he projects in a futile attempt to feel like he's part of the world around him. Isolated, bullied and disregarded by society, Fleck begins a slow descent into madness as he transforms into the criminal mastermind known as the Joker." },
            { id: 11, isRented: false, title: "Fyre", year: 2019, img: "https://m.media-amazon.com/images/M/MV5BMjQ2NzE1MjYxMV5BMl5BanBnXkFtZTgwMjM3MDQxNzM@._V1_SY1000_SX675_AL_.jpg", descrShort: "The history of the Fyre Music Festival, from its creation through its unraveling." },
            { id: 13, isRented: false, title: "Terminator: Dark Fate", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/5/5f/Terminator_Dark_Fate_poster.jpg", descrShort: "Sarah Connor and a hybrid cyborg human must protect a young girl from a newly modified liquid Terminator from the future." },
            { id: 12, isRented: false, title: "Fast & Furious Presents: Hobbs & Shaw", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/0/00/Fast_%26_Furious_Presents_Hobbs_%26_Shaw_-_theatrical_poster.jpg", descrShort: "DescriptionBrixton Lorr is a cybernetically enhanced soldier who possesses superhuman strength, a brilliant mind and a lethal pathogen that could wipe out half of the world's population. It's now up to hulking lawman Luke Hobbs and lawless operative Deckard Shaw to put aside their past differences and work together to prevent the seemingly indestructible Lorr from destroying humanity." },
            { id: 9, isRented: false, title: "Jumanji: The Next Level", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/3/3c/JumanjiTheNextLevelTeaserPoster.jpg", descrShort: "The four players brave the jungle, desert, mountains and dangerous animals to save the fantastical video game world of Jumanji." },
            { id: 16, isRented: false, title: "John Wick: Chapter 3", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/9/94/John_Wick_Chapter_3_Parabellum.png", descrShort:" After gunning down a member of the High Table  the shadowy international assassins guild -- legendary hit man John Wick finds himself stripped of the organizations protective services. Now stuck with a $14 million bounty on his head, Wick must fight his way through the streets of New York as he becomes the target of the worlds most ruthless killers." },
            { id: 7, isRented: false, title: "Money Heist", year: 2019, img: "https://m.media-amazon.com/images/M/MV5BNmYxZWNlMDAtYzczZC00M2ViLWIwYjctMDg3M2QyN2E1MzlmXkEyXkFqcGdeQXVyNjE4ODA3NTY@._V1_SY1000_CR0,0,675,1000_AL_.jpg", descrShort: "A criminal mastermind who goes by: The Professor has a plan to pull off the biggest heist in recorded history -- to print billions of euros in the Royal Mint of Spain. To help him carry out the ambitious plan, he recruits eight people with certain abilities and who have nothing to lose. The group of thieves take hostages to aid in their negotiations with the authorities, who strategize to come up with a way to capture The Professor. As more time elapses, the robbers prepare for a showdown with the police." },
            { id: 14, isRented: false, title: "Rambo, Last Blood", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/b/b1/Rambo_-_Last_Blood_official_theatrical_poster.jpg", descrShort: "Vietnam War veteran John Rambo tries to find some semblance of peace by raising horses on a ranch in Arizona. He's also developed a special familial bond with a woman named Maria and her teenage granddaughter Gabriela. But when a vicious Mexican cartel kidnaps Gabriela, Rambo crosses the border on a bloody and personal quest to rescue her and punish those responsible." },
            { id: 7, isRented: false, title: "Toy Story 4", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/4/4c/Toy_Story_4_poster.jpg", descrShort: "Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky. The adventurous journey turns into an unexpected reunion as Woody's slight detour leads him to his long-lost friend Bo Peep. As Woody and Bo discuss the old days, they soon start to realize that they're worlds apart when it comes to what they want from life as a toy." },
            { id: 20, isRented: false, title: "Game Night", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/a/a4/Game_Night_%28film%29.png", descrShort:" Max and Annie's weekly game night gets kicked up a notch when Max's brother Brooks arranges a murder mystery party -- complete with fake thugs and federal agents. So when Brooks gets kidnapped, it's all supposed to be part of the game. As the competitors set out to solve the case, they start to learn that neither the game nor Brooks are what they seem to be. The friends soon find themselves in over their heads as each twist leads to another unexpected turn over the course of one chaotic night." },
            { id: 19, isRented: false, title: "Annihilation", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/f/f6/Annihilation_%28film%29.png", descrShort:"Lena, a biologist and former soldier, joins a mission to uncover what happened to her husband inside Area X -- a sinister and mysterious phenomenon that is expanding across the American coastline. Once inside, the expedition discovers a world of mutated landscapes and creatures, as dangerous as it is beautiful, that threatens both their lives and their sanity. " },
            { id: 18, isRented: false, title: "Mission: Impossible – Fallout", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/f/ff/MI_%E2%80%93_Fallout.jpg", descrShort:" Ethan Hunt and the IMF team join forces with CIA assassin August Walker to prevent a disaster of epic proportions. Arms dealer John Lark and a group of terrorists known as the Apostles plan to use three plutonium cores for a simultaneous nuclear attack on the Vatican, Jerusalem and Mecca, Saudi Arabia. When the weapons go missing, Ethan and his crew find themselves in a desperate race against time to prevent them from falling into the wrong hands." },
            { id: 17, isRented: false, title: "Venom", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/1/18/Venom_%282018_film_poster%29.png", descrShort:"Journalist Eddie Brock is trying to take down Carlton Drake, the notorious and brilliant founder of the Life Foundation. While investigating one of Drake's experiments, Eddie's body merges with the alien Venom -- leaving him with superhuman strength and power. Twisted, dark and fueled by rage, Venom tries to control the new and dangerous abilities that Eddie finds so intoxicating. " },
            { id: 10, isRented: false, title: "Ocean's 8", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/d/dd/OceansEightPoster.jpeg", descrShort: "Five years, eight months, 12 days and counting -- that's how long Debbie Ocean has been devising the biggest heist of her life. She knows what it's going to take -- a team of the best people in the field, starting with her partner-in-crime Lou Miller. Together, they recruit a crew of specialists, including jeweler Amita, street con Constance, suburban mom Tammy, hacker Nine Ball, and fashion designer Rose. Their target -- a necklace that's worth more than $150 million." },
            { id: 1, isRented: false, title: "The Lion King",year: 2018, img: "https://img00.deviantart.net/b782/i/2006/207/e/7/the_lion_king_front_cd_cover_by_peachpocket285.jpg", year: 1994, descrShort: "A young lion prince named Simba is born into wealth but raised into incredible misfortune. Trickster uncle, dying father, usurpation. Luckily, an unlikely meerkat-warthog pair take him in and teach him The Ways of the Bum Life. Be prepared for ghostly hallucinations, wild baboons, creepy crawlies." },
            { id: 8, isRented: false, title: "Fast and furious 8", year: 2017, img: "https://m.media-amazon.com/images/M/MV5BMjA2MDM2OTc0MV5BMl5BanBnXkFtZTgwMTg2MzQ4MDI@._V1_.jpg", descrShort: "With Dom and Letty married, Brian and Mia retired and the rest of the crew exonerated, the globe-trotting team has found some semblance of a normal life. They soon face an unexpected challenge when a mysterious woman named Cipher forces Dom to betray them all. Now, they must unite to bring home the man who made them a family and stop Cipher from unleashing chaos." },
            { id: 5, isRented: false, title: "Coco", year: 2017, img: "https://upload.wikimedia.org/wikipedia/en/9/98/Coco_%282017_film%29_poster.jpg", descrShort: "Despite his family's generations-old ban on music, young Miguel dreams of becoming an accomplished musician like his idol Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead." },
            { id: 4, isRented: false, title: "Beauty and the Beast", year: 2016, img: "https://images-na.ssl-images-amazon.com/images/I/51ArFYSFGJL.jpg", descrShort: "Basically the same as the original, except now Hermi-- Emma Wattson plays Belle, fittingly so some would say, given how actively progressive she is regarding women's rights. Rumor has it that in the bonus scenes she whips out a wand and turns Gaston into a toad, but in order to watch those scenes you need to recite a certain incantation." },
            { id: 6, isRented: false, title: "Moana", year: 2016, img: "https://upload.wikimedia.org/wikipedia/en/2/26/Moana_Teaser_Poster.jpg", descrShort: "An adventurous teenager sails out on a daring mission to save her people. During her journey, Moana meets the once-mighty demigod Maui, who guides her in her quest to become a master way-finder. Together they sail across the open ocean on an action-packed voyage, encountering enormous monsters and impossible odds. Along the way, Moana fulfills the ancient quest of her ancestors and discovers the one thing she always sought: her own identity." },
            { id: 2, isRented: false, title: "Beauty and the Beast", year: 1991, img: "https://images-na.ssl-images-amazon.com/images/I/81etFyb9N-L._SL1500_.jpg", descrShort: "A kickass woman named Belle who does not succumb to social norms gets crap from a bunch of village idiots, chief amongst them a total tool named Gaston. Belle shows everyone how great she is when she turns a beast (not Gaston) into a man. Love ensues, but then the villagers fall trap to severe group-think mentality led by the main tool himself." },
            { id: 0, isRented: false, title: "Tarzan", year: 1999, img: "https://vignette.wikia.nocookie.net/disney-fan-fiction/images/4/42/Tarzan_2004_cover.jpg/revision/latest?cb=20140331030811", descrShort: "Tarzan was born into wealth but raised into incredible misfortune. Shiprweck, parents mauled by a jaguar. Luckily, a troop of gorillas took him in, but the Big Daddy gorilla never took a liking to him. That is, until the end when it's too late. Why is it too late? Watch and find out." },
           
            
          ],
          rentedMovies: 0,
          budget: 200
        },
        user4: {
          name: "Pete",
          movies: [
            { id: 15, isRented: false, title: "Joker", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg", descrShort: "Forever alone in a crowd, failed comedian Arthur Fleck seeks connection as he walks the streets of Gotham City. Arthur wears two masks -- the one he paints for his day job as a clown, and the guise he projects in a futile attempt to feel like he's part of the world around him. Isolated, bullied and disregarded by society, Fleck begins a slow descent into madness as he transforms into the criminal mastermind known as the Joker." },
            { id: 11, isRented: false, title: "Fyre", year: 2019, img: "https://m.media-amazon.com/images/M/MV5BMjQ2NzE1MjYxMV5BMl5BanBnXkFtZTgwMjM3MDQxNzM@._V1_SY1000_SX675_AL_.jpg", descrShort: "The history of the Fyre Music Festival, from its creation through its unraveling." },
            { id: 12, isRented: false, title: "Fast & Furious Presents: Hobbs & Shaw", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/0/00/Fast_%26_Furious_Presents_Hobbs_%26_Shaw_-_theatrical_poster.jpg", descrShort: "DescriptionBrixton Lorr is a cybernetically enhanced soldier who possesses superhuman strength, a brilliant mind and a lethal pathogen that could wipe out half of the world's population. It's now up to hulking lawman Luke Hobbs and lawless operative Deckard Shaw to put aside their past differences and work together to prevent the seemingly indestructible Lorr from destroying humanity." },
            { id: 13, isRented: false, title: "Terminator: Dark Fate", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/5/5f/Terminator_Dark_Fate_poster.jpg", descrShort: "Sarah Connor and a hybrid cyborg human must protect a young girl from a newly modified liquid Terminator from the future." },
            { id: 9, isRented: false, title: "Jumanji: The Next Level", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/3/3c/JumanjiTheNextLevelTeaserPoster.jpg", descrShort: "The four players brave the jungle, desert, mountains and dangerous animals to save the fantastical video game world of Jumanji." },
            { id: 16, isRented: false, title: "John Wick: Chapter 3", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/9/94/John_Wick_Chapter_3_Parabellum.png", descrShort:" After gunning down a member of the High Table  the shadowy international assassins guild -- legendary hit man John Wick finds himself stripped of the organizations protective services. Now stuck with a $14 million bounty on his head, Wick must fight his way through the streets of New York as he becomes the target of the worlds most ruthless killers." },
            { id: 7, isRented: false, title: "Money Heist", year: 2019, img: "https://m.media-amazon.com/images/M/MV5BNmYxZWNlMDAtYzczZC00M2ViLWIwYjctMDg3M2QyN2E1MzlmXkEyXkFqcGdeQXVyNjE4ODA3NTY@._V1_SY1000_CR0,0,675,1000_AL_.jpg", descrShort: "A criminal mastermind who goes by: The Professor has a plan to pull off the biggest heist in recorded history -- to print billions of euros in the Royal Mint of Spain. To help him carry out the ambitious plan, he recruits eight people with certain abilities and who have nothing to lose. The group of thieves take hostages to aid in their negotiations with the authorities, who strategize to come up with a way to capture The Professor. As more time elapses, the robbers prepare for a showdown with the police." },
            { id: 14, isRented: false, title: "Rambo, Last Blood", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/b/b1/Rambo_-_Last_Blood_official_theatrical_poster.jpg", descrShort: "Vietnam War veteran John Rambo tries to find some semblance of peace by raising horses on a ranch in Arizona. He's also developed a special familial bond with a woman named Maria and her teenage granddaughter Gabriela. But when a vicious Mexican cartel kidnaps Gabriela, Rambo crosses the border on a bloody and personal quest to rescue her and punish those responsible." },
            { id: 7, isRented: false, title: "Toy Story 4", year: 2019, img: "https://upload.wikimedia.org/wikipedia/en/4/4c/Toy_Story_4_poster.jpg", descrShort: "Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky. The adventurous journey turns into an unexpected reunion as Woody's slight detour leads him to his long-lost friend Bo Peep. As Woody and Bo discuss the old days, they soon start to realize that they're worlds apart when it comes to what they want from life as a toy." },
            { id: 20, isRented: false, title: "Game Night", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/a/a4/Game_Night_%28film%29.png", descrShort:" Max and Annie's weekly game night gets kicked up a notch when Max's brother Brooks arranges a murder mystery party -- complete with fake thugs and federal agents. So when Brooks gets kidnapped, it's all supposed to be part of the game. As the competitors set out to solve the case, they start to learn that neither the game nor Brooks are what they seem to be. The friends soon find themselves in over their heads as each twist leads to another unexpected turn over the course of one chaotic night." },
            { id: 19, isRented: false, title: "Annihilation", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/f/f6/Annihilation_%28film%29.png", descrShort:"Lena, a biologist and former soldier, joins a mission to uncover what happened to her husband inside Area X -- a sinister and mysterious phenomenon that is expanding across the American coastline. Once inside, the expedition discovers a world of mutated landscapes and creatures, as dangerous as it is beautiful, that threatens both their lives and their sanity. " },
            { id: 18, isRented: false, title: "Mission: Impossible – Fallout", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/f/ff/MI_%E2%80%93_Fallout.jpg", descrShort:" Ethan Hunt and the IMF team join forces with CIA assassin August Walker to prevent a disaster of epic proportions. Arms dealer John Lark and a group of terrorists known as the Apostles plan to use three plutonium cores for a simultaneous nuclear attack on the Vatican, Jerusalem and Mecca, Saudi Arabia. When the weapons go missing, Ethan and his crew find themselves in a desperate race against time to prevent them from falling into the wrong hands." },
            { id: 17, isRented: false, title: "Venom", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/1/18/Venom_%282018_film_poster%29.png", descrShort:"Journalist Eddie Brock is trying to take down Carlton Drake, the notorious and brilliant founder of the Life Foundation. While investigating one of Drake's experiments, Eddie's body merges with the alien Venom -- leaving him with superhuman strength and power. Twisted, dark and fueled by rage, Venom tries to control the new and dangerous abilities that Eddie finds so intoxicating. " },
            { id: 10, isRented: false, title: "Ocean's 8", year: 2018, img: "https://upload.wikimedia.org/wikipedia/en/d/dd/OceansEightPoster.jpeg", descrShort: "Five years, eight months, 12 days and counting -- that's how long Debbie Ocean has been devising the biggest heist of her life. She knows what it's going to take -- a team of the best people in the field, starting with her partner-in-crime Lou Miller. Together, they recruit a crew of specialists, including jeweler Amita, street con Constance, suburban mom Tammy, hacker Nine Ball, and fashion designer Rose. Their target -- a necklace that's worth more than $150 million." },
            { id: 1, isRented: false, title: "The Lion King",year: 2018, img: "https://img00.deviantart.net/b782/i/2006/207/e/7/the_lion_king_front_cd_cover_by_peachpocket285.jpg", year: 1994, descrShort: "A young lion prince named Simba is born into wealth but raised into incredible misfortune. Trickster uncle, dying father, usurpation. Luckily, an unlikely meerkat-warthog pair take him in and teach him The Ways of the Bum Life. Be prepared for ghostly hallucinations, wild baboons, creepy crawlies." },
            { id: 8, isRented: false, title: "Fast and furious 8", year: 2017, img: "https://m.media-amazon.com/images/M/MV5BMjA2MDM2OTc0MV5BMl5BanBnXkFtZTgwMTg2MzQ4MDI@._V1_.jpg", descrShort: "With Dom and Letty married, Brian and Mia retired and the rest of the crew exonerated, the globe-trotting team has found some semblance of a normal life. They soon face an unexpected challenge when a mysterious woman named Cipher forces Dom to betray them all. Now, they must unite to bring home the man who made them a family and stop Cipher from unleashing chaos." },
            { id: 5, isRented: false, title: "Coco", year: 2017, img: "https://upload.wikimedia.org/wikipedia/en/9/98/Coco_%282017_film%29_poster.jpg", descrShort: "Despite his family's generations-old ban on music, young Miguel dreams of becoming an accomplished musician like his idol Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead." },
            { id: 4, isRented: false, title: "Beauty and the Beast", year: 2016, img: "https://images-na.ssl-images-amazon.com/images/I/51ArFYSFGJL.jpg", descrShort: "Basically the same as the original, except now Hermi-- Emma Wattson plays Belle, fittingly so some would say, given how actively progressive she is regarding women's rights. Rumor has it that in the bonus scenes she whips out a wand and turns Gaston into a toad, but in order to watch those scenes you need to recite a certain incantation." },
            { id: 6, isRented: false, title: "Moana", year: 2016, img: "https://upload.wikimedia.org/wikipedia/en/2/26/Moana_Teaser_Poster.jpg", descrShort: "An adventurous teenager sails out on a daring mission to save her people. During her journey, Moana meets the once-mighty demigod Maui, who guides her in her quest to become a master way-finder. Together they sail across the open ocean on an action-packed voyage, encountering enormous monsters and impossible odds. Along the way, Moana fulfills the ancient quest of her ancestors and discovers the one thing she always sought: her own identity." },
            { id: 2, isRented: false, title: "Beauty and the Beast", year: 1991, img: "https://images-na.ssl-images-amazon.com/images/I/81etFyb9N-L._SL1500_.jpg", descrShort: "A kickass woman named Belle who does not succumb to social norms gets crap from a bunch of village idiots, chief amongst them a total tool named Gaston. Belle shows everyone how great she is when she turns a beast (not Gaston) into a man. Love ensues, but then the villagers fall trap to severe group-think mentality led by the main tool himself." },
            { id: 0, isRented: false, title: "Tarzan", year: 1999, img: "https://vignette.wikia.nocookie.net/disney-fan-fiction/images/4/42/Tarzan_2004_cover.jpg/revision/latest?cb=20140331030811", descrShort: "Tarzan was born into wealth but raised into incredible misfortune. Shiprweck, parents mauled by a jaguar. Luckily, a troop of gorillas took him in, but the Big Daddy gorilla never took a liking to him. That is, until the end when it's too late. Why is it too late? Watch and find out." },
           
            
          ],
          rentedMovies: 0,
          budget: 150
        }
      }
    }

  }

  rent = (id, user) => {
    if (this.state.users[user].budget >= 25) {
      let users = {...this.state.users}

      users[user].movies.find(m => m.id == + id).isRented = true
      users[user].rentedMovies = this.state.users[user].rentedMovies + 1 
      users[user].budget = this.state.users[user].budget - 25
      
  
      this.setState({ users: users })
    }

  }

  unrent = (id, user) => {
    
    let users = {...this.state.users}

    users[user].movies.find(m => m.id == + id).isRented = false
    users[user].rentedMovies = this.state.users[user].rentedMovies - 1 
    users[user].budget = this.state.users[user].budget + 25

    this.setState({ users: users })
  }

  storeUser = (user) =>{
    this.setState({actualUser: user})

  }
  render() {
    return (
      <Router>
        <Route path="/:user" render={({ match }) => <Header users={this.state.users} match={match} />} />
        <Route exact path="/" render={() => <Landing users={this.state.users}/>} />
        <Route exact path="/:user/catalog" render={({ match }) => <Catalog match={match} users={this.state.users} unrent={this.unrent} rent={this.rent} rentedMovies={this.state.rentedMovies} />} />
        <Route exact path="/:user/movies/:id" render={({ match }) => <MovieDetail match={match} users={this.state.users} />} />

      </Router>
    )
  }
}


export default App;
